# Generated by Django 4.2.1 on 2023-07-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0002_rename_patologias_paciente_histo_med_and_more'),
        ('consulta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='ev_gang_linf',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='fc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='fr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='mucosa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='pc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='receta',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tllc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='comentarios',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pacientes.paciente'),
        ),
    ]
