# Generated by Django 4.2.1 on 2023-07-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_app', '0002_consulta_ev_gang_linf_consulta_fc_consulta_fr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='mucosa',
            new_name='color_mucosa',
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='humedad_mucosa',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
