# Generated by Django 4.2.2 on 2023-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_app', '0003_rename_mucosa_consulta_color_mucosa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='comportamiento',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='movilidad',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nutricion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='pelaje',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='piel',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='postura',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
