# Generated by Django 4.2.1 on 2023-07-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_app', '0005_remove_consulta_comportamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateField(),
        ),
    ]
