# Generated by Django 4.2.1 on 2023-07-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='patologias',
            new_name='histo_med',
        ),
        migrations.AddField(
            model_name='paciente',
            name='vacunas',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
