# Generated by Django 4.2.1 on 2023-07-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('no_calle', models.IntegerField()),
                ('nro_dpto_casa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_tutor', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('id_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vet_APP.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=255)),
                ('patologias', models.CharField(max_length=10000, null=True)),
                ('esterilizado', models.CharField(max_length=255)),
                ('comentarios', models.CharField(max_length=10000, null=True)),
                ('rut_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vet_APP.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField()),
                ('motivo_consulta', models.CharField(max_length=10000)),
                ('comentarios', models.CharField(max_length=100000)),
                ('id_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vet_APP.paciente')),
            ],
        ),
    ]
